#pragma config(Motor,  port1,           a,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           b,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           c,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           d,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           e,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           f,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           g,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           h,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           i,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          j,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		if(vexRT[Btn6U]==1){
			motor[a]=127;
			motor[b]=127;
			motor[c]=127;
			motor[d]=127;
			motor[e]=127;
			motor[f]=127;
			motor[g]=127;
			motor[h]=127;
			motor[i]=127;
			motor[j]=127;
			} else{
			motor[a]=0;
			motor[b]=0;
			motor[c]=0;
			motor[d]=0;
			motor[e]=0;
			motor[f]=0;
			motor[g]=0;
			motor[h]=0;
			motor[i]=0;
			motor[j]=0;
		}
	}
}
