#pragma config(Motor,  port7,           a,             tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
if(vexRT[Btn6U]==1){
			motor[a]=127;
			} else{
			motor[a]=0;
		}
	}
}
